### PR TITLE
convert to lazy val to fix a problem when compiled with GraalVM Nativ…

### PR DESCRIPTION
**Pull request by mio-19**
…e image and class init at build time

https://github.com/com-lihaoyi/os-lib/issues/318

### CODE REVIEW

**Comment by lihaoyi** [comment]
Probably going to call this a wontfix

**Comment by j-mie6** [comment]
How come? is it a binary break?

**Comment by SethTisue** [comment]
@j-mie6 see discussion on #318

**Comment by j-mie6** [comment]
Fair enough!

**Pull request closed without merging**
