### PR TITLE
Delete `ConcurrentLinkedQueue`

### PR DESCRIPTION
**Pull request by armanbilge**
This is now in Scala Native javalib.

### CODE REVIEW

**Comment by lefou** [comment]
It seems this fixes https://github.com/com-lihaoyi/os-lib/issues/117 and it looks reasonable to me. Although, I have no idea at which point in time this class was added to Scala native directly, and whether there is a chance to break some users code. Our binary checks suggest, it won't, at least not for the same set of versions. Maybe @lolgab can review this one, as he initially added this class.

**Comment by armanbilge** [comment]
Great point. This has been there since Scala Native 0.4.0.

https://github.com/scala-native/scala-native/issues/1993

Since that was a breaking release with entirely new artifacts I think we can be confident that this won't break anybody.

**Comment by lefou** [comment]
Thanks @armanbilge. Looks good to merge then.

**Comment by lolgab** [comment]
Thank you for the fix @armanbilge and for merging @lefou.

**Pull request merged**
