### PR TITLE
Retry flaky tests

### PR DESCRIPTION
**Pull request by lolgab**
This retries the flaky watch tests we have

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
10 retries looks a bit too high and reduces my confidence.

Also, maybe we should make this conditional or configurable, e.g. by an env var `TEST_RETRY_COUNT` which we set in the build? We could check for `CI` or `GITHUB_ACTIONS` (https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), so that we don't retry when testing locally (and possibly shadow malfunction).

**Comment by lolgab** [comment]
I tried with 5 and it failed on Mac OS. Actually I can configure the retry to 10 only on mac and on Github Actions. What do you think @lefou ?

**Comment by lefou** [comment]
I think Linux is also failing sometimes. If you retry only on GITHUB, I'm fine with it.

**Review by lefou — APPROVED** [review]
LGTM.

**Pull request merged**
