### PR TITLE
Prefer File.getCanonicalFile over Path.normalize

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/com-lihaoyi/os-lib/issues/78.

### CODE REVIEW

**Comment by alexarchambault** [comment]
This might be a problem if people use os-lib with non-standard file systems, like NIO allows… Sometimes, the `Path` from these file systems correspond to purely virtual things, and cannot be converted to a concrete `File`. Don't know if that's a use case that os-lib should handle…

**Review by lefou — COMMENTED** [review]
Looks good to me. Having a test for it, would make me more comfortable.

**Comment by alexarchambault** [comment]
> Having a test for it, would make me more comfortable.

Same for me, actually… I'll try to add one the next time I'll boot my Windows machine.

**Comment by alexarchambault** [comment]
Ok, I added a test… and now I'm shared about merging this 😬

`File.getCanonicalFile` depends on what's on disk, so that two calls of `os.Path(…).toString` may not return the same value (if we pass it a short form, it will return a longer one, but only when the corresponding file exists), which could be surprising.

Also, it seems `File.getCanonicalFile` caches its values: if it's called with a short form before the file exists, it will later always return the short form, even if we create the underlying file later on. Which is equally surprising.

`Path.normalize` doesn't suffer those quirks, AFAIK.


And fwiw, a similar issue can be reproduced on macOS (with its "case-insensitive but case-preserving" file systems), using just the case:
```text
$ mkdir Foo && amm -c 'println((os.pwd / "foo").toIO.getCanonicalFile)'
/Users/alexandre/test/Foo

$ rmdir Foo && amm -c 'println((os.pwd / "foo").toIO.getCanonicalFile); os.makeDir(os.pwd / "Foo"); println((os.pwd / "foo").toIO.getCanonicalFile)'
/Users/alexandre/test/foo
/Users/alexandre/test/foo

$ ls
Foo
```

**Comment by lefou** [comment]
> Ok, I added a test… and now I'm shared about merging this grimacing

Do you mean "scared"?

> `File.getCanonicalFile` depends on what's on disk, so that two calls of `os.Path(…).toString` may not return the same value (if we pass it a short form, it will return a longer one, but only when the corresponding file exists), which could be surprising.

Oh, as I commented on #78, I'd rather remove any dependency on disk state, and I was under the impression, you're going to always normalize to the long form. In that regard, I don't understand the test case, at least, it test something different.

> But a worse issue is that it seems that `File.getCanonicalFile` caches its values: if it's called with a short form before the file exists, it will later always return the short form, even if we create the underlying file later on.
> 
> `Path.normalize` doesn't suffer those quirks, AFAIK.

Better, we don't merge this.

**Comment by alexarchambault** [comment]
It'd be better not to merge, yes.

(And it seems there's a need for a library providing true canonical paths, without those caching quirks…)

**Pull request closed without merging**
